### ISSUE TITLE
not working on ONKYO TX-NR905

### ISSUE THREAD

**Issue by czosnekltd** [arturpragacz/hass-cc-onkyo-dev#3]
It does not work (like standard integration) with Onkyo TX-NR905.
I was forced to install the version https://github.com/mtdcr/homeassistant-onky-lagacy which is still working.

If there is a need, I can send some logs, etc. to help in debugging.

**Comment by arturpragacz** [comment]
Instead please just read the documentation: https://www.home-assistant.io/integrations/onkyo

You can find there which receivers are supported at this point.
